# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{classifier}
  s.version = "0.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Lucas Carlson"]
  s.date = %q{2013-04-09}
  s.description = %q{A general classifier module to allow Bayesian and other types of classifications.}
  s.email = %q{lucas@rufy.com}
  s.executables = ["bayes.rb", "summarize.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README",
    "Rakefile",
    "VERSION",
    "bin/bayes.rb",
    "bin/summarize.rb",
    "classifier.gemspec",
    "install.rb",
    "lib/classifier.rb",
    "lib/classifier/bayes.rb",
    "lib/classifier/extensions/string.rb",
    "lib/classifier/extensions/vector.rb",
    "lib/classifier/extensions/vector_serialize.rb",
    "lib/classifier/extensions/word_hash.rb",
    "lib/classifier/lsi.rb",
    "lib/classifier/lsi/content_node.rb",
    "lib/classifier/lsi/summary.rb",
    "lib/classifier/lsi/word_list.rb",
    "test/bayes/bayesian_test.rb",
    "test/extensions/word_hash_test.rb",
    "test/lsi/lsi_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = %q{http://classifier.rufy.com}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A general classifier module to allow Bayesian and other types of classifications.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<fast-stemmer>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<yard>, ["~> 0.7"])
    else
      s.add_dependency(%q<fast-stemmer>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<yard>, ["~> 0.7"])
    end
  else
    s.add_dependency(%q<fast-stemmer>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<yard>, ["~> 0.7"])
  end
end

